#=require jquery/dist/jquery
#=require bootstrap
#=require facebox/src/facebox
#=require qrcodejs/qrcode
#=require tagcloud/jquery.tagcloud
#=require jquery-timeago/jquery.timeago
#=require jquery-timeago/locales/jquery.timeago.zh-CN
#=require_tree .
#=require_self
