# Override theme next

scheme: Pisces

avatar:
  # Replace the default image and set the url here.
  url: https://avatars0.githubusercontent.com/u/944583?v=4&s=460

social:
  GitHub: https://github.com/wongyouth || fab fa-github

github_banner:
  enable: false
  permalink: https://github.com/wongyouth

# Disqus
disqus:
  enable: true
  shortname: wongyouth
