postgresql:
  image: postgres
  environment:
    - POSTGRES_USER=redmine
    - POSTGRES_PASSWORD=redmine
    - PGDATA=/data
  volumes:
    - /data/pg:/data
  restart: always
  
redmine:
  image: quay.io/sameersbn/redmine:latest
  links:
    - postgresql:postgresql
  environment:
    #- REDMINE_VERSION=3.0.1
    - USERMAP_UID=1001
    - USERMAP_GID=1001
    - TZ=Asia/Beijing
    - REDMINE_PORT=3000
    - SMTP_ENABLED=true
    - SMTP_DOMAIN=jiaoxuebang.com
    - SMTP_HOST=smtp.exmail.qq.com
    - SMTP_PORT=25
    - SMTP_USER=red@jiaoxuebang.com
    - SMTP_PASS=redmine123456
    #- SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login
    - IMAP_ENABLED=false
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_SSL=true
    - IMAP_INTERVAL=30
    - UNICORN_TIMEOUT=300
    - NGINX_MAX_UPLOAD_SIZE=100m
  ports:
    - "80:80"
  volumes:
    - /data/redmine:/home/redmine/data
    - /home/git/repositories:/home/redmine/repositories
  restart: always
